CREATE TABLE TODO (
    TODO_ID  SERIAL  ,
    USER_ID  INT ,
    PRIMARY KEY(TODO_ID)
);

CREATE TABLE TODOELEMENT (
    ELEMENT_ID  SERIAL,
    TODO_ID  INT NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    COMPLETED BOOLEAN,
    SORT_ORDER INT,
    PRIMARY KEY(ELEMENT_ID)
);

CREATE TABLE USERS (
    ID  SERIAL,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);