CREATE TABLE TODO (
    ID INT PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    COMPLETED BOOLEAN,
    `ORDER` INT
    );

CREATE TABLE USER (
    ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL
    );